require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MilestonesController do

  def mock_milestone(stubs={})
    @mock_milestone ||= mock_model(Milestone, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all milestones as @milestones" do
      Milestone.stub(:all) { [mock_milestone] }
      get :index
      assigns(:milestones).should eq([mock_milestone])
    end
  end

  describe "GET show" do
    it "assigns the requested milestone as @milestone" do
      Milestone.stub(:find).with("37") { mock_milestone }
      get :show, :id => "37"
      assigns(:milestone).should be(mock_milestone)
    end
  end

  describe "GET new" do
    it "assigns a new milestone as @milestone" do
      Milestone.stub(:new) { mock_milestone }
      get :new
      assigns(:milestone).should be(mock_milestone)
    end
  end

  describe "GET edit" do
    it "assigns the requested milestone as @milestone" do
      Milestone.stub(:find).with("37") { mock_milestone }
      get :edit, :id => "37"
      assigns(:milestone).should be(mock_milestone)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created milestone as @milestone" do
        Milestone.stub(:new).with({'these' => 'params'}) { mock_milestone(:save => true) }
        comment :create, :milestone => {'these' => 'params'}
        assigns(:milestone).should be(mock_milestone)
      end

      it "redirects to the created milestone" do
        Milestone.stub(:new) { mock_milestone(:save => true) }
        comment :create, :milestone => {}
        response.should redirect_to(milestone_url(mock_milestone))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved milestone as @milestone" do
        Milestone.stub(:new).with({'these' => 'params'}) { mock_milestone(:save => false) }
        comment :create, :milestone => {'these' => 'params'}
        assigns(:milestone).should be(mock_milestone)
      end

      it "re-renders the 'new' template" do
        Milestone.stub(:new) { mock_milestone(:save => false) }
        comment :create, :milestone => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested milestone" do
        Milestone.stub(:find).with("37") { mock_milestone }
        mock_milestone.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :milestone => {'these' => 'params'}
      end

      it "assigns the requested milestone as @milestone" do
        Milestone.stub(:find) { mock_milestone(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:milestone).should be(mock_milestone)
      end

      it "redirects to the milestone" do
        Milestone.stub(:find) { mock_milestone(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(milestone_url(mock_milestone))
      end
    end

    describe "with invalid params" do
      it "assigns the milestone as @milestone" do
        Milestone.stub(:find) { mock_milestone(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:milestone).should be(mock_milestone)
      end

      it "re-renders the 'edit' template" do
        Milestone.stub(:find) { mock_milestone(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested milestone" do
      Milestone.stub(:find).with("37") { mock_milestone }
      mock_milestone.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the milestones list" do
      Milestone.stub(:find) { mock_milestone }
      delete :destroy, :id => "1"
      response.should redirect_to(milestones_url)
    end
  end

end
