source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'bundler'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3-ruby', :require => 'sqlite3'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19'

# Bundle the extra gems:
gem 'formtastic'
gem "paperclip", "~> 2.3"
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end

group :development do
  gem "jquery-rails" # Setup jQuery and jQuery UI in rails app (run 'rails generate jquery:install --ui' to setup)
                     # Don't forget to output csrf_meta_tag somewhere inside your <head> tag in your layout!
  gem 'rails3-generators' # Generators for DataMapper, Factory-girl, Authlogic, Mongomapper, Shoulda, Formtastic and SimpleForm, etc...
end

group :test do
  gem "rspec-rails", ">= 2.0.1"
  gem 'factory_girl_rails'
  # gem 'remarkable', '>=4.0.0.alpha2'
  # gem 'remarkable_activemodel', '>=4.0.0.alpha2'
  # gem 'remarkable_activerecord', '>=4.0.0.alpha2'
  # gem 'ci_reporter' 
  gem "cucumber-rails"
  gem "capybara"
  gem 'database_cleaner'
end